# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUI_2.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.setEnabled(True)
        Form.resize(1169, 767)
        Form.setMinimumSize(QSize(1169, 767))
        Form.setMaximumSize(QSize(1169, 767))
        self.capture = QPushButton(Form)
        self.capture.setObjectName(u"capture")
        self.capture.setGeometry(QRect(20, 510, 191, 31))
        self.image_feed = QLabel(Form)
        self.image_feed.setObjectName(u"image_feed")
        self.image_feed.setGeometry(QRect(9, 9, 640, 480))
        self.image_feed.setMinimumSize(QSize(640, 480))
        self.image_feed.setMaximumSize(QSize(640, 480))
        self.image_feed.setScaledContents(True)
        self.live_prediction = QRadioButton(Form)
        self.live_prediction.setObjectName(u"live_prediction")
        self.live_prediction.setGeometry(QRect(720, 120, 121, 31))
        self.capture_2 = QPushButton(Form)
        self.capture_2.setObjectName(u"capture_2")
        self.capture_2.setGeometry(QRect(220, 510, 191, 31))
        self.accuracy = QTextBrowser(Form)
        self.accuracy.setObjectName(u"accuracy")
        self.accuracy.setGeometry(QRect(580, 610, 241, 31))
        self.epochs = QLineEdit(Form)
        self.epochs.setObjectName(u"epochs")
        self.epochs.setGeometry(QRect(580, 500, 241, 31))
        self.progressBar_2 = QProgressBar(Form)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(930, 500, 241, 31))
        self.progressBar_2.setValue(24)
        self.model_name = QLineEdit(Form)
        self.model_name.setObjectName(u"model_name")
        self.model_name.setGeometry(QRect(580, 720, 371, 31))
        self.count = QTextBrowser(Form)
        self.count.setObjectName(u"count")
        self.count.setGeometry(QRect(90, 700, 241, 31))
        self.line = QFrame(Form)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(450, 510, 20, 261))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.loss = QTextBrowser(Form)
        self.loss.setObjectName(u"loss")
        self.loss.setGeometry(QRect(580, 660, 241, 31))
        self.label_11 = QLabel(Form)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(480, 670, 61, 16))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 590, 52, 16))
        self.label.setFont(font)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(480, 510, 45, 16))
        self.label_5.setFont(font)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 640, 33, 16))
        self.label_2.setFont(font)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 710, 38, 16))
        self.label_3.setFont(font)
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(480, 620, 61, 16))
        self.label_8.setFont(font)
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(850, 510, 71, 16))
        self.label_7.setFont(font)
        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(480, 730, 72, 16))
        self.label_9.setFont(font)
        self.class_name = QLineEdit(Form)
        self.class_name.setObjectName(u"class_name")
        self.class_name.setGeometry(QRect(90, 640, 241, 31))
        self.Dataset = QLineEdit(Form)
        self.Dataset.setObjectName(u"Dataset")
        self.Dataset.setGeometry(QRect(90, 580, 241, 31))
        self.evaluate = QPushButton(Form)
        self.evaluate.setObjectName(u"evaluate")
        self.evaluate.setGeometry(QRect(730, 560, 91, 31))
        self.load_model = QPushButton(Form)
        self.load_model.setObjectName(u"load_model")
        self.load_model.setGeometry(QRect(1020, 720, 101, 31))
        self.train = QPushButton(Form)
        self.train.setObjectName(u"train")
        self.train.setGeometry(QRect(580, 560, 91, 31))
        self.save_model = QPushButton(Form)
        self.save_model.setObjectName(u"save_model")
        self.save_model.setGeometry(QRect(1020, 680, 101, 31))
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(720, 180, 65, 16))
        self.label_4.setFont(font)
        self.label_10 = QLabel(Form)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(720, 260, 71, 16))
        self.label_10.setFont(font)
        self.prediction = QTextBrowser(Form)
        self.prediction.setObjectName(u"prediction")
        self.prediction.setGeometry(QRect(807, 170, 341, 41))
        self.confidence = QTextBrowser(Form)
        self.confidence.setObjectName(u"confidence")
        self.confidence.setGeometry(QRect(810, 240, 341, 41))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"TATA_Motors-Model trainer and Predictor", None))
        self.capture.setText(QCoreApplication.translate("Form", u"Capture", None))
        self.image_feed.setText("")
        self.live_prediction.setText(QCoreApplication.translate("Form", u"LIVE PREDICTION", None))
        self.capture_2.setText(QCoreApplication.translate("Form", u"Cancel", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"Loss", None))
        self.label.setText(QCoreApplication.translate("Form", u"Dataset", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"Epochs", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Class", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Count", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Accuracy", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Progress", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Model path", None))
        self.evaluate.setText(QCoreApplication.translate("Form", u"Evaluate", None))
        self.load_model.setText(QCoreApplication.translate("Form", u"Load model", None))
        self.train.setText(QCoreApplication.translate("Form", u"Train", None))
        self.save_model.setText(QCoreApplication.translate("Form", u"Save model", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Prediction", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Confidence", None))
    # retranslateUi

